name: ZerDisguise
version: 2.5.5
main: me.zerith.zerdisguise.ZerDisguise
api-version: "1.20"
description: Plugin de disfraces con GUI interactiva — v2.5.5
author: zerinho23
softdepend:
  -ProtocolLib
  - Vault
  - LuckPerms
  - PlaceholderAPI

commands:
  disguise:
    description: Abre el menu de disfraces
    usage: /<command> [remove|reload|<jugador>]
    permission: zerdisguise.use
    aliases:
      - disfraz
      - zd
      - zerdisguise

  undisguise:
    description: Quita el disfraz activo rapidamente
    usage: /<command>
    permission: zerdisguise.use
    aliases:
      - quitardisfraz
      - removedisguise

permissions:
  zerdisguise.use:
    description: Usar el menu de disfraces
    default: true
  zerdisguise.others:
    description: Abrir el menu de disfraz de otro jugador
    default: op
  zerdisguise.reload:
    description: Recargar la configuracion
    default: op
  zerdisguise.bypass:
    description: No puede ser disfrazado por otros (proteccion)
    default: false
  zerdisguise.rank.default:
    description: Puede seleccionar el rango default
    default: true
  zerdisguise.rank.vip:
    description: Puede seleccionar el rango VIP
    default: op
  zerdisguise.rank.mod:
    description: Puede seleccionar el rango Mod
    default: op
  zerdisguise.rank.admin:
    description: Puede seleccionar el rango Admin
    default: op
  zerdisguise.rank.owner:
    description: Puede seleccionar el rango Owner
    default: op
